# Generated by Django 2.0 on 2017-12-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rptmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
